// next/src/components/Book.tsx
import Link from "next/link";

interface BookProps {
  link?: boolean;
  href?: string;
  book: any;
}

export default function Book({ link, href, book }: BookProps) {
  function formatDate(string: string) {
    return string.replace(/ .*/, "").slice(2);
  }

  const classNames =
    "relative h-96 bg-neutral-100 flex items-center justify-center p-2 rounded-lg hover:bg-[#EEEEF0] transition-colors group";
  const innerElements = (
    <>
      <img
        className="w-32 md:w-36 lg:w-40 group-hover:-translate-y-1 transition-transform ease-in-out shadow-lg drop-shadow-lg"
        src={book.img}
        alt={book.title}
      />
      <div className="absolute bottom-3 left-3 right-3 flex justify-between items-end">
        <div>
          <small className="block text-neutral-400">{book.author}</small>
          <p className="text-sm line-clamp-1">{book.title}</p>
        </div>
        <div className="text-neutral-400 text-right">
          <small className="block text-sm">{book.status}</small>
          {book.status === "read" ? (
            <small className="block">{formatDate(book.finished)}</small>
          ) : null}
        </div>
      </div>
    </>
  );

  if (link === false) {
    return <div className={classNames}>{innerElements}</div>;
  } else if (href) {
    return (
      <Link href={href} className={`${classNames} hover:cursor-pointer`}>
        {innerElements}
      </Link>
    );
  }
}

// sveltekit/src/lib/components/Book.svelte
<script lang="ts">
  import type { BookType } from "$lib/types";
  export let book: BookType;
  export let status: boolean = false;

  function formatDate(string: string) {
    return string.replace(/ .*/, "").slice(2);
  }
</script>

<div
  class="relative md:h-96 bg-neutral-100 flex gap-5 items-center justify-start md:justify-center p-4 md:p-2 rounded-lg hover:bg-[#EEEEF0] transition-colors group"
>
  <img
    class="w-24 md:w-36 lg:w-40 group-hover:-translate-y-1 transition-transform ease-in-out shadow-lg drop-shadow-lg"
    src={book.img}
    alt={book.title}
  />
  <div
    class="md:absolute md:bottom-3 md:left-3 md:right-3 flex justify-between items-end"
  >
    <div>
      <small class="block text-neutral-400">{book.author}</small>
      <p class="text-sm line-clamp-2 md:line-clamp-1">{book.title}</p>
    </div>
    <div
      class="absolute bottom-3 left-3 right-3 md:relative md:bottom-0 md:left-0 md:right-0 text-neutral-400 text-right"
    >
      {#if status}
        <small class="block text-sm">{book.status}</small>
      {/if}
      {#if book.status === "read"}
        <small class="block">{formatDate(book.finished)}</small>
      {/if}
    </div>
  </div>
</div>
