// src/routes/Add.jsx
import { useLocation } from "react-router-dom";
import Layout from "../components/Shared/Layout";
import Title from "../components/Shared/Title";
import Back from "../components/UI/Back";
import CreateEdit from "../components/Shared/CreateEdit";

export default function Add({ pb, user }) {
  const location = useLocation();
  const locationBook = location.state.book;

  return (
    <Layout variant={"small"}>
      <Back to="/search" />
      <Title title={"Add a book"} description="You can edit the infos below." />
      <CreateEdit book={locationBook} pb={pb} userID={user.record.id} />
    </Layout>
  );
}

// src/routes/add/+page.svelte
<script lang="ts">
  import BackIcon from "$lib/components/BackIcon.svelte";
  import CreateEdit from "$lib/components/CreateEdit.svelte";
  import Layout from "$lib/components/Layout.svelte";
  import Title from "$lib/components/Title.svelte";
  export let data;
  const { book } = data;
</script>

<Layout small={true}>
  <BackIcon href="/search" />
  <Title title="Add a book" description="You can edit the infos below." />
  <CreateEdit {book} />
</Layout>
