// src/routes/signin/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import BackIcon from "$lib/components/BackIcon.svelte";
  import ErrorMessage from "$lib/components/Form/ErrorMessage.svelte";
  import FormContainer from "$lib/components/Form/FormContainer.svelte";
  import Input from "$lib/components/Form/Input.svelte";
  import InputContainer from "$lib/components/Form/InputContainer.svelte";
  import Label from "$lib/components/Form/Label.svelte";
  import Submit from "$lib/components/Form/Submit.svelte";
  import SubmitContainer from "$lib/components/Form/SubmitContainer.svelte";
  import Layout from "$lib/components/Layout.svelte";
  import Title from "$lib/components/Title.svelte";

  export let data;

  let errorMessage: string | null = null;

  let formData = {
    email: "",
    password: "",
  };

  let loading = false;

  async function login() {
    const { supabase } = data;
    loading = true;
    errorMessage = null;

    const { error } = await supabase.auth.signInWithPassword({
      email: formData.email,
      password: formData.password,
    });

    if (error) {
      errorMessage = error.message;
      loading = false;
      return;
    }

    goto("/");
    loading = false;
  }
</script>

<Layout small={true}>
  <BackIcon href="/" />
  <Title
    title="Login"
    description="Sign in with the credential provided. If you don't have one, please contant via the button on the homepage."
  />
  <FormContainer onSubmit={login}>
    <InputContainer>
      <Label htmlFor="email">Email</Label>
      <Input
        required={true}
        type="email"
        placeholder="yourname@email.com"
        bind:value={formData.email}
      />
    </InputContainer>
    <InputContainer>
      <Label htmlFor="password">Password</Label>
      <Input
        required={true}
        type="password"
        placeholder="Your password"
        bind:value={formData.password}
      />
    </InputContainer>
    <SubmitContainer>
      <Submit value={"Sign In"} bind:loading />
      {#if errorMessage}
        <ErrorMessage message={errorMessage} />
      {/if}
    </SubmitContainer>
  </FormContainer>
</Layout>

// src/routes/SignIn.jsx
import { useEffect, useRef } from "react";
import { supabase } from "../supabase";
import Layout from "../components/Shared/Layout";
import Back from "../components/UI/Back";
import Title from "../components/Shared/Title";
import FormContainer from "../components/UI/Form/FormContainer";
import InputContainer from "../components/UI/Form/InputContainer";
import Label from "../components/UI/Form/Label";
import Input from "../components/UI/Form/Input";
import Submit from "../components/UI/Form/Submit";

export default function SignIn({ user, loading, setLoading }) {
  const emailRef = useRef();
  const passwordRef = useRef();

  async function login(event) {
    setLoading(true);
    event.preventDefault();
    const { error } = await supabase.auth.signInWithPassword({
      email: emailRef.current.value,
      password: passwordRef.current.value,
    });

    if (error) {
      alert(error.error_description || error.message);
    }

    setLoading(false);
  }

  useEffect(() => {
    if (user) window.location.href = "/";
  }, [user]);

  return (
    <Layout variant={"small"}>
      <Back to="/" />
      <Title
        title={"Login"}
        description={
          "Sign in with the credential provided. If you don't have one, please contant via the button on the homepage."
        }
      />
      <FormContainer onSubmit={login}>
        <InputContainer>
          <Label htmlFor="email">Email</Label>
          <Input
            required={true}
            type="email"
            placeholder="yourname@email.com"
            inputRef={emailRef}
          />
        </InputContainer>
        <InputContainer>
          <Label htmlFor="email">Password</Label>
          <Input
            required={true}
            type="password"
            placeholder="Your password"
            inputRef={passwordRef}
          />
        </InputContainer>
        <Submit value={"Sign In"} loading={loading} />
      </FormContainer>
    </Layout>
  );
}
