// sveltekit/src/lib/components/Header.svelte
<script lang="ts">
  import { browser } from "$app/environment";
  import { goto } from "$app/navigation";
  export let data: any;
  $: ({ supabase, session } = data);

  async function logout() {
    const { error } = await supabase.auth.signOut();

    if (error) {
      console.log(error);
    }

    if (browser) {
      window.location.reload();
    }
  }
</script>

<header
  class="fixed top-0 left-0 right-0 h-12 px-3 py-4 mx-2 flex justify-between items-center border-b border-neutral-100 bg-white/75 backdrop-blur z-10"
>
  <nav class="flex gap-4">
    <a class="text-sm underline italic" href="/"> Index </a>
  </nav>
  <nav>
    {#if session}
      <button
        class="text-sm text-neutral-400 hover:underline"
        on:click={logout}
      >
        Logout
      </button>
    {:else}
      <a class="text-sm text-neutral-400 hover:underline" href="/signin">
        Sign In
      </a>
    {/if}
  </nav>
</header>

// next-app/src/components/Header.tsx
"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useUser, useSupabaseClient } from "@supabase/auth-helpers-react";

export default function Header() {
  const user = useUser();
  const supabase = useSupabaseClient();
  const router = useRouter();

  function logout() {
    supabase.auth.signOut();
    router.push("/");
  }

  return (
    <header className="fixed top-0 left-0 right-0 h-12 px-3 py-4 mx-2 flex justify-between items-center border-b border-neutral-100 bg-white/75 backdrop-blur z-10">
      <div className="flex gap-4">
        <Link className="text-sm underline italic" href="/">
          Index
        </Link>
        {user ? (
          <Link
            className="text-sm text-neutral-400 hover:underline"
            href="/search"
          >
            Search
          </Link>
        ) : null}
      </div>
      <nav>
        {user ? (
          <button
            className="text-sm text-neutral-400 hover:underline"
            onClick={() => logout()}
          >
            Logout
          </button>
        ) : (
          <Link
            className="text-sm text-neutral-400 hover:underline"
            href="/signin"
          >
            Sign In
          </Link>
        )}
      </nav>
    </header>
  );
}
