// next-app/src/components/Form/Input.tsx
import { InputHTMLAttributes } from "react";

interface InputProps {
  type: string;
  required: boolean;
  placeholder: string;
  defaultValue?: string;
  inputRef?: any;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
}

export default function Input({
  type,
  required,
  placeholder,
  defaultValue,
  inputRef,
  onChange,
}: InputProps) {
  return (
    <input
      className="text-sm shrink grow"
      type={type}
      required={required}
      placeholder={placeholder}
      defaultValue={defaultValue}
      ref={inputRef}
      onChange={onChange}
    />
  );
}

// src/lib/components/Form/Input.svelte
<script lang="ts">
  export let type: string = "text";
  export let required: boolean = true;
  export let placeholder: string = "";
  export let value: string | null = null;
  export let onChange = () => {};

  const handleInput = (e: Event) => {
    const target = e.target as HTMLInputElement;
    value = target.value;
  };
</script>

<input
  class="shrink grow border-none p-0 text-sm focus-within:ring-0 focus:outline-none focus:ring-0"
  {type}
  {required}
  {placeholder}
  {value}
  on:change|preventDefault={onChange}
  on:input={handleInput}
/>
