// src/components/Shared/CreateEdit.jsx
import { useEffect, useRef, useState } from "react";
import FormContainer from "../UI/Form/FormContainer";
import InputContainer from "../UI/Form/InputContainer";
import Label from "../UI/Form/Label";
import Input from "../UI/Form/Input";
import Submit from "../UI/Form/Submit";

export default function CreateEdit({
  pb,
  userID,
  book,
  bookID,
  children,
  loading,
  setLoading,
}) {
  const [bookIsFinished, setBookIsFinished] = useState(false);
  const titleRef = useRef();
  const authorRef = useRef();
  const statusRef = useRef();
  const imgRef = useRef();
  const finishedRef = useRef();

  useEffect(() => {
    if (book) {
      titleRef.current.value = book.title;
      authorRef.current.value = book.author;
      statusRef.current.value = book.status ? book.status : "to-read";
      imgRef.current.value = book.img;
      finishedRef.current.value = book.finished
        ? book.finished.replace(/ .*/, "")
        : null;
    }
  }, [book]);

  useEffect(() => {
    toggleFinishedBook();
  }, []);

  async function addBook(event) {
    event.preventDefault();
    setLoading(true);
    const data = {
      title: titleRef.current.value,
      author: authorRef.current.value,
      status: statusRef.current.value,
      img: imgRef.current.value,
      finished:
        statusRef.current.value === "read" ? finishedRef.current.value : null,
      owner: userID,
    };
    await pb.collection("books").create(data);
    setLoading(false);
    window.location.href = "/";
  }

  async function updateBook(event) {
    event.preventDefault();
    setLoading(true);
    const data = {
      title: titleRef.current.value,
      author: authorRef.current.value,
      status: statusRef.current.value,
      finished:
        statusRef.current.value === "read" ? finishedRef.current.value : null,
      img: imgRef.current.value,
    };
    await pb.collection("books").update(bookID, data);
    setLoading(false);
    window.location.href = "/";
  }

  function toggleFinishedBook() {
    if (statusRef.current.value === "read") {
      setBookIsFinished(true);
    } else {
      setBookIsFinished(false);
    }
  }

  return (
    <FormContainer onSubmit={bookID ? updateBook : addBook}>
      <div className="mb-2 bg-neutral-100 flex items-center justify-center p-10 rounded-lg">
        <img
          className="w-36 shadow-lg drop-shadow-lg"
          src={book.img}
          alt={book.title}
        />
      </div>
      <InputContainer>
        <Label htmlFor="img-url">Img URL:</Label>
        <Input
          required={true}
          type="text"
          placeholder="https://example.com/image.jpg"
          inputRef={imgRef}
        />
      </InputContainer>
      <InputContainer>
        <Label htmlFor="title">Title</Label>
        <Input
          required={true}
          type="text"
          placeholder="Game of Thrones"
          inputRef={titleRef}
        />
      </InputContainer>
      <InputContainer>
        <Label htmlFor="author">Author</Label>
        <Input
          required={true}
          type="text"
          placeholder="George R. R. Martin"
          inputRef={authorRef}
        />
      </InputContainer>
      <InputContainer>
        <Label htmlFor="status">Status</Label>
        <select className="w-fit" ref={statusRef} onChange={toggleFinishedBook}>
          <option value="to-read">To Read</option>
          <option value="reading">Reading</option>
          <option value="read">Read</option>
        </select>
      </InputContainer>
      <InputContainer hidden={bookIsFinished ? false : true}>
        <Label htmlFor="finished">Finished</Label>
        <input type="date" ref={finishedRef} />
      </InputContainer>

      <div className="flex gap-3 items-center">
        <Submit value={`${bookID ? "Update" : "Add"}`} loading={loading} />
        {children}
      </div>
    </FormContainer>
  );
}

// src/lib/components/CreateEdit.svelte
<script lang="ts">
  import type { BookType } from "$lib/types";
  import type { ActionData } from "./$types";
  import ErrorMessage from "./Form/ErrorMessage.svelte";
  import FormContainer from "./Form/FormContainer.svelte";
  import Hearth from "./Form/Hearth.svelte";
  import Input from "./Form/Input.svelte";
  import InputContainer from "./Form/InputContainer.svelte";
  import Label from "./Form/Label.svelte";
  import Submit from "./Form/Submit.svelte";

  export let form: ActionData;
  export let book: BookType;
  export let edit = false;
  let loading = false;

  async function submit() {
    loading = true;
  }
</script>

<FormContainer onSubmit={submit}>
  <div
    class="relative mb-2 flex items-center justify-center rounded-lg bg-neutral-100 p-10"
  >
    <img
      class="w-36 shadow-lg drop-shadow-lg"
      src={book.img}
      alt={book.title}
    />
    <div class="absolute bottom-3 right-3">
      {#if book.status === "read"}
        <Hearth id={book.id} bind:checked={book.favorite} />
      {/if}
    </div>
  </div>
  <Input
    id="img"
    label="Img URL"
    required={true}
    type="text"
    placeholder="https://example.com/image.jpg"
    bind:value={book.img}
  />
  <Input
    id="title"
    label="Title"
    required={true}
    type="text"
    placeholder="Game of Thrones"
    bind:value={book.title}
  />
  <Input
    id="author"
    label="Author"
    required={true}
    type="text"
    placeholder="George R. R. Martin"
    bind:value={book.author}
  />
  <InputContainer>
    <Label htmlFor="status">Status</Label>
    <select
      id="status"
      name="status"
      class="border-none py-0 pl-0 pr-8 text-sm focus-within:ring-0 focus:outline-none focus:ring-0"
      bind:value={book.status}
      on:change={() => {
        if (book.status === "read")
          book.finished = new Date().toISOString().split("T")[0];
        else book.finished = null;

        if (book.status !== "read") book.favorite = false;
      }}
    >
      <option value="to-read">To Read</option>
      <option value="reading">Reading</option>
      <option value="read">Read</option>
    </select>
  </InputContainer>
  {#if book.status === "read"}
    <InputContainer>
      <Label htmlFor="finished">Finished</Label>
      <input
        id="finished"
        name="finished"
        required
        type="date"
        class="border-none p-0 text-sm focus-within:ring-0 focus:outline-none focus:ring-0"
        bind:value={book.finished}
      />
    </InputContainer>
  {/if}

  <div class="mb-7 mt-7 flex items-center gap-3">
    <Submit value={edit ? `Update` : `Add`} bind:loading />
    <slot />
  </div>
  {#if form?.issues || form?.errorMessage}
    <ErrorMessage issues={form.issues} message={form.errorMessage} />
  {/if}
</FormContainer>
