// next/src/components/Header.tsx
import Link from "next/link";
import { useUser, useSupabaseClient } from "@supabase/auth-helpers-react";

export default function Header() {
  const user = useUser();
  const supabase = useSupabaseClient();

  return (
    <header className="fixed top-0 left-0 right-0 h-12 px-3 py-4 mx-2 flex justify-between items-center border-b border-neutral-100 bg-white/75 backdrop-blur z-10">
      <div className="flex gap-4">
        <Link className="text-sm underline italic" href="/">
          Index
        </Link>
        {user ? (
          <Link
            className="text-sm text-neutral-400 hover:underline"
            href="/search"
          >
            Search
          </Link>
        ) : null}
      </div>
      <nav>
        {user ? (
          <button
            className="text-sm text-neutral-400 hover:underline"
            onClick={() => supabase.auth.signOut()}
          >
            Logout
          </button>
        ) : (
          <Link
            className="text-sm text-neutral-400 hover:underline"
            href="/signin"
          >
            Sign In
          </Link>
        )}
      </nav>
    </header>
  );
}

// src/lib/components/Header.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import type { Session } from "@supabase/supabase-js";

  export let session: Session | null;
</script>

<header
  class="fixed left-0 right-0 top-0 z-10 mx-2 flex h-12 items-center justify-between border-b border-neutral-100 bg-white/75 px-3 py-4 backdrop-blur"
>
  <nav class="flex justify-center gap-4">
    <a
      class="text-sm text-neutral-400 hover:underline {$page.route.id === '/'
        ? 'italic text-neutral-900 underline'
        : ''}"
      href="/"
    >
      {session ? "Reading" : "Index"}
    </a>
    {#if session}
      <a
        class="text-sm text-neutral-400 hover:underline {$page.route.id ===
        '/read'
          ? 'italic text-neutral-900 underline'
          : ''}"
        href="/read"
      >
        Read</a
      >
      <a
        class="text-sm text-neutral-400 hover:underline {$page.route.id ===
        '/to-read'
          ? 'italic text-neutral-900 underline'
          : ''}"
        href="/to-read"
      >
        To Read</a
      >
    {/if}
  </nav>
  <nav class="flex justify-center gap-4">
    {#if session}
      <a class="text-sm text-neutral-400 hover:underline" href="/search">
        Search</a
      >
      <form
        method="post"
        class="text-sm text-neutral-400 hover:underline"
        action="/logout"
      >
        <button>Logout</button>
      </form>
    {:else}
      <a class="text-sm text-neutral-400 hover:underline" href="/signin">
        Sign In
      </a>
    {/if}
  </nav>
</header>
