// src/components/Shared/Title.jsx
import { Link } from "react-router-dom";

export default function Title({ title, description, link, nopt, notitlemb }) {
  let pt = "pt-14";
  if (nopt) {
    pt = "pt-0";
  }

  let mb = "mb-2";
  if (notitlemb) {
    mb = "mb-0";
  }

  return (
    <div
      className={`flex flex-row ${pt} pb-4 gap-2 justify-between items-end ${
        link ? null : "max-w-md"
      }`}
    >
      <div>
        <h2 className={`text-2xl ${mb}`}>{title}</h2>
        <p className="text-sm text-neutral-400">{description}</p>
      </div>
      {link ? (
        <Link
          className="group text-sm text-neutral-400 hover:underline"
          to={link}
        >
          See more →
        </Link>
      ) : null}
    </div>
  );
}

// src/lib/components/Title.svelte
<script lang="ts">
  export let title: string;
  export let description: string;
  export let mb = "mb-1";
</script>

<div class="flex max-w-xs flex-row items-end justify-between gap-2 pb-4">
  <div>
    <h2 class="text-2xl {mb}">{title}</h2>
    <p class="text-sm text-neutral-400">{description}</p>
  </div>
</div>
