// src/components/Title.tsx
import Link from "next/link";

interface TitleProps {
  title: string;
  description: string;
}

export default function Title({ title, description }: TitleProps) {
  return (
    <div
      className={`flex flex-row pb-4 gap-2 justify-between items-end max-w-xs`}
    >
      <div>
        <h2 className={`text-2xl mb-1`}>{title}</h2>
        <p className="text-sm text-neutral-400">{description}</p>
      </div>
    </div>
  );
}

// src/lib/components/Title.svelte
<script lang="ts">
  export let title: string;
  export let description: string;
  export let mb = "mb-1";
</script>

<div class="flex max-w-xs flex-row items-end justify-between gap-2 pb-4">
  <div>
    <h2 class="text-2xl {mb}">{title}</h2>
    <p class="text-sm text-neutral-400">{description}</p>
  </div>
</div>
