// sveltekit/src/routes/add/+page.svelte
<script lang="ts">
  import Layout from "$lib/components/Layout.svelte";
  import BackIcon from "$lib/components/BackIcon.svelte";
  import Title from "$lib/components/Title.svelte";
  import CreateEdit from "$lib/components/CreateEdit.svelte";
  export let data;
  const { book, supabase, session }: any = data;
</script>

<Layout small={true}>
  <BackIcon href="/search" />
  <Title title="Add a book" description="You can edit the infos below." />
  <CreateEdit {book} {supabase} {session} />
</Layout>

// next/src/pages/add.tsx
import { useRouter } from "next/router";
import Layout from "@/components/Layout";
import Title from "@/components/Title";
import BackIcon from "@/components/Back";
import CreateEdit from "@/components/CreateEdit";

export default function Add() {
  const router = useRouter();
  const book = router.query;

  return (
    <Layout variant={"small"}>
      <BackIcon href="/search" />
      <Title title={"Add a book"} description="You can edit the infos below." />
      <CreateEdit book={book} />
    </Layout>
  );
}
