// sveltekit/src/routes/read/+page.svelte
<script lang="ts">
  import BackIcon from "$lib/components/BackIcon.svelte";
  import BooksContainer from "$lib/components/BooksContainer.svelte";
  import Header from "$lib/components/Header.svelte";
  import Layout from "$lib/components/Layout.svelte";
  import Title from "$lib/components/Title.svelte";
  import Book from "$lib/components/Book.svelte";
  import BookLink from "$lib/components/BookLink.svelte";
  export let data;
  const { books } = data;
</script>

<Layout>
  <Header {data} />
  <BackIcon />
  <Title title="Read" description="The last books I've read." />
  <BooksContainer>
    {#each books as book}
      <BookLink href="/book/{book.id}">
        <Book {book} status={true} />
      </BookLink>
    {/each}
  </BooksContainer>
</Layout>

// next/src/pages/read.tsx
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { GetServerSidePropsContext } from "next";
import Layout from "@/components/Layout";
import Title from "@/components/Title";
import Header from "@/components/Header";
import BackIcon from "@/components/Back";
import BooksContainer from "@/components/BooksContainer";
import Book from "@/components/Book";
import { Book as BookType } from "@/global/types";

export default function Reading({ books }: any) {
  return (
    <Layout>
      <Header />
      <BackIcon href="/" />
      <Title
        title={"Read"}
        description={"The last books I've read."}
        nopt={true}
        notitlemb={true}
      />
      <BooksContainer>
        {books
          .map((book: BookType) => {
            if (book.finished) {
              return {
                ...book,
                finishedDate: new Date(book.finished),
              };
            }
            return book;
          })
          .sort((a: any, b: any) => {
            if (a.finishedDate && b.finishedDate) {
              return b.finishedDate - a.finishedDate;
            }
            return 0;
          })
          .map((book: BookType) => (
            <Book key={book.id} href={`/book`} book={book} />
          ))}
      </BooksContainer>
    </Layout>
  );
}

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  // Create authenticated Supabase Client
  const supabase = createServerSupabaseClient(ctx);
  // Check if we have a session
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session)
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };

  // Run queries with RLS on the server
  const { data: books } = await supabase
    .from("books")
    .select()
    .eq("owner", session.user.id)
    .eq("status", "read");

  return {
    props: {
      initialSession: session,
      books: books,
    },
  };
};
