// sveltekit/src/routes/search/+page.svelte
<script lang="ts">
  import Layout from "$lib/components/Layout.svelte";
  import BackIcon from "$lib/components/BackIcon.svelte";
  import Title from "$lib/components/Title.svelte";
  import FormContainer from "$lib/components/Form/FormContainer.svelte";
  import InputContainer from "$lib/components/Form/InputContainer.svelte";
  import Label from "$lib/components/Form/Label.svelte";
  import Input from "$lib/components/Form/Input.svelte";
  import Submit from "$lib/components/Form/Submit.svelte";
  import BooksContainer from "$lib/components/BooksContainer.svelte";
  import Book from "$lib/components/Book.svelte";
  import searchBooks from "$lib/functions/search";
  import type { BookType } from "$lib/types";
  import { PUBLIC_GOOGLE_API_KEY } from "$env/static/public";

  let books = [] as BookType[];
  let loading = false;
  let noBooksMsg = false;
  let inputValues = {
    title: "",
    author: "",
    isbn: "",
  };

  async function fetchBooks() {
    try {
      loading = true;

      if (
        inputValues.title === "" &&
        inputValues.author === "" &&
        inputValues.isbn === ""
      ) {
        alert("Complete at least one field.");
        loading = false;
        return;
      }

      const res = await searchBooks(
        PUBLIC_GOOGLE_API_KEY,
        inputValues.title,
        inputValues.author,
        inputValues.isbn
      );

      if (res.data.totalItems === 0) {
        loading = false;
        noBooksMsg = true;
        return;
      }

      res.data.items = res.data.items.slice(0, 6);

      books = res.data.items.map((book: any) => {
        const title = book.volumeInfo.title;
        const author = book.volumeInfo.authors
          ? book.volumeInfo.authors[0]
          : "Unknown";
        const img = book.volumeInfo.imageLinks
          ? book.volumeInfo.imageLinks.thumbnail
          : "https://via.placeholder.com/150x150/e6e6e6/969696?text=No+Cover+Avaiable";
        return {
          title,
          author,
          img,
        };
      });

      loading = false;
    } catch (error) {
      console.log(error);
    }
  }
</script>

<Layout small={true}>
  <BackIcon href="/" />
  <Title
    title="Search"
    description="Search for a book and add it to your booklist. Complete at least one field."
  />
  <FormContainer onSubmit={fetchBooks}>
    <InputContainer>
      <Label htmlFor="title">Title</Label>
      <Input
        required={false}
        type="text"
        placeholder="Game of Thrones"
        bind:value={inputValues.title}
      />
    </InputContainer>
    <InputContainer>
      <Label htmlFor="author">Author</Label>
      <Input
        required={false}
        type="text"
        placeholder="George R.R. Martin"
        bind:value={inputValues.author}
      />
    </InputContainer>
    <InputContainer>
      <Label htmlFor="isbn">ISBN</Label>
      <Input
        required={false}
        type="text"
        placeholder="880475172X"
        bind:value={inputValues.isbn}
      />
    </InputContainer>
    <Submit value={"Search"} bind:loading />
  </FormContainer>
  <BooksContainer cols={2}>
    {#if noBooksMsg}
      <p class="text-sm">No books found! Do another search.</p>
    {:else}
      {#each books as book}
        <Book {book} />
      {/each}
    {/if}
  </BooksContainer>
</Layout>

// next/src/pages/search.tsx
import { useRef, useState } from "react";
import searchBooks from "@/functions/search";
import Layout from "@/components/Layout";
import BackIcon from "@/components/Back";
import FormContainer from "@/components/Form/FormContainer";
import InputContainer from "@/components/Form/InputContainer";
import Label from "@/components/Form/Label";
import Input from "@/components/Form/Input";
import Submit from "@/components/Form/Submit";
import BooksContainer from "@/components/BooksContainer";
import Book from "@/components/Book";
import Title from "@/components/Title";

export default function Search() {
  const api_key = process.env.NEXT_PUBLIC_GOOGLE_API_KEY;
  const [loading, setLoading] = useState(false);
  const [searchedBooks, setSearchedBooks] = useState([]);
  const [noBooksMsg, setNoBooksMsg] = useState(false);
  const titleRef: any = useRef();
  const authorRef: any = useRef();
  const ISBNRef: any = useRef();

  async function fetchBooks(e: React.FormEvent<HTMLFormElement>) {
    try {
      setLoading(true);
      setNoBooksMsg(false);
      setSearchedBooks([]);
      e.preventDefault();

      if (
        titleRef.current.value === "" &&
        authorRef.current.value === "" &&
        ISBNRef.current.value === ""
      ) {
        setLoading(false);
        return;
      }

      const response = await searchBooks(api_key, titleRef, authorRef, ISBNRef);

      if (response.data.totalItems === 0) {
        setLoading(false);
        setNoBooksMsg(true);
        return;
      }

      let books =
        response.data.items.length > 6
          ? response.data.items.slice(0, 6)
          : response.data.items;
      setSearchedBooks(books);
      setLoading(false);
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <Layout variant={"small"}>
      <BackIcon href="/" />
      <Title
        title={"Search"}
        description={
          "Search for a book and add it to your booklist. Complete at least one field."
        }
        nopt={true}
      />
      <FormContainer onSubmit={fetchBooks}>
        <InputContainer>
          <Label htmlFor="title">Title</Label>
          <Input
            required={false}
            type="text"
            placeholder="Game of Thrones"
            inputRef={titleRef}
          />
        </InputContainer>
        <InputContainer>
          <Label htmlFor="author">Author</Label>
          <Input
            required={false}
            type="text"
            placeholder="George R.R. Martin"
            inputRef={authorRef}
          />
        </InputContainer>
        <InputContainer>
          <Label htmlFor="isbn">ISBN</Label>
          <Input
            required={false}
            type="text"
            placeholder="880475172X"
            inputRef={ISBNRef}
          />
        </InputContainer>
        <Submit value={"Search"} loading={loading} />
      </FormContainer>
      <BooksContainer cols={2}>
        {noBooksMsg ? (
          <p className="text-sm">
            No books found!<br></br>Do another search.
          </p>
        ) : (
          <>
            {searchedBooks.map((searchedBook: any) => {
              const book = {
                id: searchedBook.id,
                title: searchedBook.volumeInfo.title,
                author: searchedBook.volumeInfo.authors
                  ? searchedBook.volumeInfo.authors[0]
                  : "Unknown",
                img: searchedBook.volumeInfo.imageLinks
                  ? searchedBook.volumeInfo.imageLinks.thumbnail
                  : "https://via.placeholder.com/150x150/e6e6e6/969696?text=No+Cover+Avaiable",
              };

              return <Book key={book.id} href={`/add`} book={book} />;
            })}
          </>
        )}
      </BooksContainer>
    </Layout>
  );
}
