// sveltekit/src/routes/signin/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import BackIcon from "$lib/components/BackIcon.svelte";
  import Layout from "$lib/components/Layout.svelte";
  import Title from "$lib/components/Title.svelte";
  import FormContainer from "$lib/components/Form/FormContainer.svelte";
  import InputContainer from "$lib/components/Form/InputContainer.svelte";
  import Label from "$lib/components/Form/Label.svelte";
  import Input from "$lib/components/Form/Input.svelte";
  import Submit from "$lib/components/Form/Submit.svelte";

  export let data;

  let formData = {
    email: "",
    password: "",
  };

  let loading = false;

  async function login() {
    const { supabase } = data;
    loading = true;

    const { error } = await supabase.auth.signInWithPassword({
      email: formData.email,
      password: formData.password,
    });

    if (error) {
      alert(error.message);
      loading = false;
      return;
    }

    goto("/");
    loading = false;
  }
</script>

<Layout small={true}>
  <BackIcon href="/" />
  <Title
    title="Login"
    description="Sign in with the credential provided. If you don't have one, please contant via the button on the homepage."
  />
  <FormContainer onSubmit={login}>
    <InputContainer>
      <Label htmlFor="email">Email</Label>
      <Input
        required={true}
        type="email"
        placeholder="yourname@email.com"
        bind:value={formData.email}
      />
    </InputContainer>
    <InputContainer>
      <Label htmlFor="password">Password</Label>
      <Input
        required={true}
        type="password"
        placeholder="Your password"
        bind:value={formData.password}
      />
    </InputContainer>
    <Submit value={"Sign In"} bind:loading />
  </FormContainer>
</Layout>

// next/src/pages/signin.tsx
import { useRef, useState } from "react";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import { useRouter } from "next/router";
import Layout from "@/components/Layout";
import BackIcon from "@/components/Back";
import Title from "@/components/Title";
import FormContainer from "@/components/Form/FormContainer";
import InputContainer from "@/components/Form/InputContainer";
import Label from "@/components/Form/Label";
import Input from "@/components/Form/Input";
import Submit from "@/components/Form/Submit";

export default function SignIn() {
  const supabase = useSupabaseClient();
  const router = useRouter();
  const emailRef: any = useRef();
  const passwordRef: any = useRef();
  const [loading, setLoading] = useState(false);

  interface LoginEvent extends React.FormEvent<HTMLFormElement> {
    preventDefault: () => void;
  }

  async function login(event: LoginEvent) {
    setLoading(true);
    event.preventDefault();

    const { error } = await supabase.auth.signInWithPassword({
      email: emailRef.current.value,
      password: passwordRef.current.value,
    });

    if (error) {
      alert(error.message);
      setLoading(false);
      return;
    }

    router.push("/");
    setLoading(false);
  }

  return (
    <Layout variant="small">
      <BackIcon href="/" />
      <Title
        title={"Login"}
        description={
          "Sign in with the credential provided. If you don't have one, please contant via the button on the homepage."
        }
        nopt={true}
      />
      <FormContainer onSubmit={login}>
        <InputContainer>
          <Label htmlFor="email">Email</Label>
          <Input
            required={true}
            type="email"
            placeholder="yourname@email.com"
            inputRef={emailRef}
          />
        </InputContainer>
        <InputContainer>
          <Label htmlFor="email">Password</Label>
          <Input
            required={true}
            type="password"
            placeholder="Your password"
            inputRef={passwordRef}
          />
        </InputContainer>
        <Submit value={"Sign In"} loading={loading} />
      </FormContainer>
    </Layout>
  );
}
